** Summary
Lido DAO governance currently relies on Aragon voting model. This means DAO approves proposals by direct governance token voting.  
This approach does not reflect the decision making process within smaller sub governance groups formed within Lido DAO, e.g. validators committee. 
Many validators commitee decisions only relate to a small group of DAO members. Although being critical for Lido, votings on such decisions often struggle to attract DAO attraction and thus, to pass.

Easy Track is designed to solve this problem. Easy Track is a lightweight voting model where voting is considered to have passed if objections threshold hasn't been reached. As opposed to traditional Aragon votings, Easy Track is cheaper (no need to vote ‘pro’, DAO members only have to vote 'contra' if they have any objections) and more reliable (no risk of voting not exceeding minimum approval threshold).

First proposed Easy Track use case for Lido is running this type of votings to increase node operators’ staking limits. 
Easy Track votings to increase staking limits can be initiated or canceled by approved and trusted DAO node operators. 
Gnosis Safe Multisig should be used to create a node operators' multisig wallet for voting initiation.

** Easy Track contract
Easy Track contract is ownable. Contract owner can update Easy Track parameters (i.e. objections threshold to cancel the voting, approved multisig address, voting duration).
